name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync to cPanel Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync files to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        if: env.FTP_SERVER != ''
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/sales-agent.toolsfinity.io/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
